spring:
  datasource:
    #   数据源基本配置
    username: root
    password: tptogiar
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/_study?characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true

