
#person:
#  lastName: hello
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu



server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
  port: 8068
spring:
  profiles: dev


---

server:
  port: 8084
spring:
  profiles: prod  #指定属于哪个环境

